name: presence_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: 1.20.0
  get: 4.6.5
  firebase_auth: 3.5.1
  cloud_firestore: 3.4.1
  image_picker: 0.8.5+3
  firebase_storage: 10.3.3
  convex_bottom_bar: 3.0.0
  intl: 0.17.0
  geolocator: 9.0.1
  geocoding: 2.0.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

